[[headers]]
  for = "/favicon.ico"
  [headers.values]
    Content-Type = "image/x-icon"
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/favicon.png"
  [headers.values]
    Content-Type = "image/png"
    Cache-Control = "public, max-age=86400"
